name: covers2colors
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - matplotlib
  - numpy
  - kneed
  - pillow
  - scikit-learn
  - scipy
  - fuzzywuzzy
  - discogs-client
  - musicbrainzngs
  - pylast
  - requests
